name: TokenShop
main: me.toxiccoke.tokenshop.TokenShop
version: 0.1
description: This is an example description
author: ToxiccokeIsGay
depend: [ServerCore]
commands:
    shop:
        description: Does shoppy things
        usage: /<command>
        permission: tokenshop.shop
    givecoins:
        description: Gives coins freely
        aliases: [givecoin]
        usage: /<command> [coins] (player)
        permission: tokenshop.give
    hatshop:
        description: Shops for hats, give gaben your money
        usage: /<command>
        permission: tokenshop.hatshop
        aliases: [hat,hats]
    coins:
        aliases: [coin]
        description: Displays how many coins you have
        usage: /<command>
    petshop:
        description: Shops for pets, give gaben your money
        usage: /<command>
        permission: tokenshop.petshop
        aliases: [pet,pets]
        