name: ServerCore
version: 1.0
main: me.toxiccoke.servercore.Commands
author: toxiccoke
description: Server Core Commands
commands:
    ap:
    gm:
        description: Sets Gamemode
        aliases: [gamemode]
        usage: /<command> 0/1
        permission: sc.gm
    fly:
        description: Turns fly on/off
        usage: /<command>
        permission: toxiccoke.fly
    heal:
        usage: /<command>
        description: Restores health to full
    tp:
        usage: /<command> [player]
        description: Teleports player
    warn:
        usage: /<command> [player] [message]
        description: Issues warning to player
    day:
        usage: /<command>
        description: Sets time to day
    night:
        usage: /<command>
        description: Sets time to night
    sun:
        usage: /<command>
        description: Sets weather so sun
    rain:
        usage: /<command>
        description: Sets weather to rain
    spawn:
        usage: /<command>
        description: Teleports to spawn
    setspawn:
        usage: /<command>
        description: Changes the spawn location
    ban:
        usage: /<command> [player] (reason)
        description: Banishes a player
    kick:
        usage: /<command> [player] (reason)
        description: Kicks player from server
    poke:
        usage: /<command> [player]
        description: Give your friends a gay gesture
#    help:
#        usage: /<command> (page)
#        description: Shows help page
    nick:
        usage: /<command> (nickname)
        description: Changes nickname
    vanish:
        usage: /<command>
        description: Vanishes
        aliases: [v]
    party:
        usage: /<command>
        description: Party Commands
        aliases: [p]
    friend:
        usage: /<command>
        description: Friend Commands
        aliases: [f,friends]

