name: BomberMiniGame
version: 1.0
main: me.toxiccoke.minigames.MiniGamesPlugin
author: Serge Humphrey
description: MiniGames plugin
depends: [WorldEdit, GroupManager]
commands:
    bomber:
        permission: bomberminigame.admin
        description: Minigame world info
        usage: /<list|create|delete>
    bconfig:
        permission: bomberminigame.admin
        description: Configures a minigame world
        usage: /<command>
        
    leave:
        description: Leaves minigame
        usage: /<command>
