name: MiniGames
version: 1.0
main: me.toxiccoke.minigames.MiniGamesPlugin
author: Serge Humphrey
description: MiniGames plugin
depends: [TokenShop, ServerCore]
commands:
    madmin:
        permission: minigames.admin
        description: Configures a minigame world
        usage: /<command>
    leave:
    party:
        usage: /<command>
        description: Party Commands
        aliases: [p]
    padmin:
        permission: minigames.admin
        description: Configures a Payload game world
        usage: /<command>
