name: Blitzkrieg
version: 1.1_2
main: me.toxiccoke.minigames.MiniGamesPlugin
author: Serge Humphrey
description: Blitzkrieg MiniGame plugin
depends: [WorldEdit]
commands:
    bomber:
        permission: bomberminigame.admin
        description: Minigame world info
        usage: /<list|create|delete>
    bconfig:
        permission: bomberminigame.admin
        description: Configures a minigame world
        usage: /<command>
        
    leave:
        description: Leaves minigame
        usage: /<command>
